### ISSUE TITLE
Tracking with Delayed_job 

### ISSUE THREAD

**Issue by echan00** [mixpanel/mixpanel-ruby#34]
I've got mixpanel tracking on delayed jobs but it seems like the events aren't being sent properly.

Some controller:
Mixpaneltracking.instance.signup(@user.id)

Mixpanel.rb: 
def signup(id)
  @mixpanel.track(id, "Sign Up")
end
handle_asynchronously :signup

**Comment by peternixey** [comment]
I had the same problem. I used the proxy method but the job kept failing regardless. The problem was though that I hadn't defined the proxy method in a way that delayed_jobs could actually see it. I simply defined it in the Rails console. 

The fix was to create a `mixpanel.rb` initializer file and include:

    class ProxyConsumer
      def self.transmit(*args)
        Mixpanel::Consumer.new.send(*args)
      end
    end

    MixTracker = Mixpanel::Tracker.new(CONFIG['mixpanel_key']) do |*message|
      ProxyConsumer.delay.transmit(*message)
    end

I then restarted the jobs processor and with this in place it successfully sent jobs over.
