### ISSUE TITLE
Consumer#import always sets time to now instead of user defined

### ISSUE THREAD

**Issue by eric-surfeasy** [mixpanel/mixpanel-ruby#52]
Hi,
I would like to make a script to import old events for a new event I am creating. Unfortunately with how import is implemented it always sets the time when the event occured to when the script is run, not when the event actually happened.

Thanks,
Eric

**Comment by zyskowsk** [comment]
Hey @eric-surfeasy, thanks for the note!  The way we like to handle this case is that you can override any of the default properties by passing a key value pair in with your additional properties when you call import.  In this case you can pass a different timestamp in and the event will be sent to Mixpanel with that timestamp instead of the system time of the method call.  I have proposed some new copy and a new test to make this more obvious in #70, which I will merge in the next release.  If you have any further questions please feel free to voice them here!

**Comment by zyskowsk** [comment]
addressed in #77
