### ISSUE TITLE
Set HTTP connection timeouts

### ISSUE THREAD

**Issue by jonleighton** [mixpanel/mixpanel-ruby#60]
I have been affected by the [downtime tonight](https://twitter.com/mixpanelstatus/status/565254094001299458) in a particularly bad way. We send some events in background jobs. These jobs started to hang, and so our queues backed up.

The underlying cause seems to be that Net::HTTP has a default `open_timeout` of `nil` (i.e. unlimited). Due to the downtime, the requests to Mixpanel's API were simply hanging.

I think the default in Net::HTTP is pretty bad. But to shield Mixpanel users from problems caused by API downtime I suggest that this library could/should set a default timeout so that requests don't hang indefinitely.

**Comment by joeatwork** [comment]
This is right on- it's a bug to wait forever on a dead connection.

In the mean time, the library provides a couple of ways to work around the problem and configure your own HTTP backend. The simplest fix might be to use `Mixpanel.config_http` if you'd just like to adjust the parameters of the default HTTP layer- something like this

```rb
Mixpanel.config_http do |http|
  http.open_timeout = 1
end
```

You can take a look at the FaradayConsumer in https://github.com/mixpanel/mixpanel-ruby/blob/master/demo/faraday_consumer.rb for a heavier weight example.

That said, a default timeout of *never* is just not sensible, and if people really want that we should let them configure it using the tools, rather than defaulting to it. I'm marking this as a bug, and I'll do my best to get a fix into the next release.

**Comment by joeatwork** [comment]
Fixed by @greysteil in 1.7.0, which I released to rubygems just now. Thanks for the heads up!
