### ISSUE TITLE
delete_user not working

### ISSUE THREAD

**Issue by daniel-nelson** [mixpanel/mixpanel-ruby#94]
delete_user (https://github.com/mixpanel/mixpanel-ruby/blob/master/lib/mixpanel-ruby/people.rb#L205-L213) always returns false for me, and never deletes the user.

From my code:
```
    tracker = Mixpanel::Tracker.new(token)
    result = tracker.people.delete_user(distinct_id)
    puts "deleting #{distinct_id}: #{result}"
```
Sample output:
```
deleting 9029: false
deleting 9040: false
deleting 15236: false
deleting 3472: false
deleting 146559c382c61d-044b5fc87-32203e1e-2c600-146559c382d60: false
deleting 2367: false
deleting 3499: false
```

**Comment by zyskowsk** [comment]
Hi @daniel-nelson!  Thanks for reaching out to us.  Do you have reason to believe that this is a bug with the library and not an integration problem?  I suggest reaching out to support@mixpanel.com, they are an extremely smart and helpful bunch!

**Comment by daniel-nelson** [comment]
Hi @zyskowsk! I did reach out to them. They provided me with a pretty involved Python script instead of answering about this gem, but we're Ruby based, so I was hoping to use this gem. I've shown how I integrated it above. Does that look correct?

**Comment by zyskowsk** [comment]
Hey thanks for getting back to me!  It looks like you are hitting some sort of error when you try to make a request to the mixpanel API: https://www.dropbox.com/s/7z28o4dub1fraij/Screenshot%202015-10-22%2014.10.39.png?dl=0.  If this is still happening for you, you could create an error handler so that we can find out what exactly is causing the request to fail.  You can create a custom error handler by following the pattern describe here: https://github.com/mixpanel/mixpanel-ruby/blob/master/lib/mixpanel-ruby/error.rb.  If you continue to have problems with the gem or have any further questions please reach out again!
